### ISSUE TITLE
Alternate dataset

### ISSUE THREAD

**Issue by abhigoku10** [yongheng1991/3D-point-capsule-networks#10]
@fedassa @ShunChengWu thanks for open sourcing the wonderfull work , i had few queries
Q1 have you trained the architecture on the available other dataset like semanttic Kitti and 3D dataset
Q2 If not trained can we follow the same training pipeline , if trained can you please share the pre-trained model
Q3 can we use the currently pre-trained model to test on custom dataset which less number of point cloud density

Thanks in advance

**Comment by ShunChengWu** [comment]
@abhigoku10 hi thanks for the interest of this work. However, I am not the main author of this work. 

@yongheng1991 you may want to see this?

**Comment by tolgabirdal** [comment]
@abhigoku10 
Our networks are not directly applicable to large 3D datasets of unconstrained scenes. How one can generalize to such datasets also depends on the application. A typical way would be to first use a segmentation network and then use our auto-encoder to tackle a downstream task. There could be other ways too. However, these are directions we have not explored and cannot provide any trained model.
