### ISSUE TITLE
bug in eval_seg code ?

### ISSUE THREAD

**Issue by jeannotes** [yongheng1991/3D-point-capsule-networks#11]
hi, really thanks for your amazing work, but I notice that "eval_seg.py", 

> parser.add_argument('--class_choice',

if class_choice is assigned "Mug", "Airplane", whatever,  then in your dataloader, cls is alwayes "0"
https://github.com/yongheng1991/3D-point-capsule-networks/blob/master/dataloaders/shapenet_part_loader.py#L30
 and then it affects "objcats", then "object2setofoid",then "iou_oids", then "part_label".

am I right

**Comment by yongheng1991** [comment]
Hi,
The "class_choice" is usually used for visualization of a specific category.  If you want to get the quantitative evaluation results for all the categories, please set the "class_choice" to "None".  And  "objects", "object2setofoid","iou_oids", "part_label" are also used for full category evaluation.
Best,
Yongheng

**Comment by jeannotes** [comment]
@yongheng1991 @tolgabirdal 
hi, if I have a new dataset which is bed but it is not in your catogory, how could I train to get segmentation result?
1. merge bed data in shapenet part dataset, and train from scratch to get latent space?
2. train autoencoder with only bed data then get bed latent space, and then train bed segmentation?

which is better?

**Comment by yongheng1991** [comment]
I think both of them would work. You could try both to see which is better.
