### ISSUE TITLE
NameError: name 'PointCloud' is not defined

### ISSUE THREAD

**Issue by CrystalBio** [yongheng1991/3D-point-capsule-networks#12]
Thanks for sharing your amazing code!
When ran through the viz_reconstruction.py, 

File "viz_reconstruction.py", line 61, in <module>
    pcd_ = PointCloud()
NameError: name 'PointCloud' is not defined

Any idea how to solve it? Thanks for your time

**Comment by yongheng1991** [comment]
Hi,
This is because of the new version of Open3D. You need to follow the new  [open3d visualization tutorial](http://www.open3d.org/docs/release/tutorial/Basic/).
Best,
