### ISSUE TITLE
point cloud viewer

### ISSUE THREAD

**Issue by zztianzz** [yongheng1991/3D-point-capsule-networks#4]
How does the picture of point cloud generate in your paper? Thanks~

**Comment by tolgabirdal** [comment]
All point clouds in our paper are results of a simple rendering in meshlab (with transparent background) and a 2D shading we add as post-processing.

**Comment by Kyle-YK-Yu** [comment]
I am not  good at using  meshlab，can u tell me how to add a 2D shading by using meshlab？

**Comment by tolgabirdal** [comment]
You can simply add 2D shading in any office program or similar 2D effects software. A better option can be 3D shading that can be added in any 3D rendering tool such as MAYA, Keyshot, Renderman etc. As this is not the point of this repository I will be closing this issue.
