### ISSUE TITLE
logger.py with TensorFlow 2.0

### ISSUE THREAD

**Issue by denabazazian** [yongheng1991/3D-point-capsule-networks#9]
If the version of TensorFlow is 2.0.0, some lines of [logger.py](https://github.com/yongheng1991/3D-point-capsule-networks/blob/master/apps/AE/logger.py) should be changed in order to monitor the training process of [train_ae.py](https://github.com/yongheng1991/3D-point-capsule-networks/blob/master/apps/AE/train_ae.py) through TensorBoard.

In [logger.py](https://github.com/yongheng1991/3D-point-capsule-networks/blob/master/apps/AE/logger.py) line [#15](https://github.com/yongheng1991/3D-point-capsule-networks/blob/master/apps/AE/logger.py#L15):

> `self.writer = tf.summary.FileWriter(log_dir)`

Should be replaced with:

> `self.writer = tf.summary.create_file_writer(log_dir)`

Also, lines [#19](https://github.com/yongheng1991/3D-point-capsule-networks/blob/master/apps/AE/logger.py#L19)  and [#20](https://github.com/yongheng1991/3D-point-capsule-networks/blob/master/apps/AE/logger.py#L20):

> `summary = tf.Summary(value=[tf.Summary.Value(tag=tag, simple_value=value)])`
>`self.writer.add_summary(summary, step)`

Should be replaced with:

> `with self.writer.as_default():`
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; `tf.summary.scalar(tag, value, step=step)`
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; `self.writer.flush()`

In the training process ([train_ae.py](https://github.com/yongheng1991/3D-point-capsule-networks/blob/master/apps/AE/train_ae.py) )of 3D Point Capsule Networks, [image_summary](https://github.com/yongheng1991/3D-point-capsule-networks/blob/master/apps/AE/logger.py#L22)  and   [histo_summary](https://github.com/yongheng1991/3D-point-capsule-networks/blob/master/apps/AE/logger.py#L45) are not used, so these two methods can be removed from [logger.py](https://github.com/yongheng1991/3D-point-capsule-networks/blob/master/apps/AE/logger.py).

**Comment by cy19980615** [comment]
after replacing with:
with self.writer.as_default():
             tf.summary.scalar(tag, value, step=step)
             self.writer.flush()
find error   'ResourceSummaryWriter' object has no attribute 'add_summary'
how to deal with it

**Comment by cy19980615** [comment]
thanks!!!!!!!!!!!!!
